# Generated by Django 4.1.6 on 2023-02-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cane', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='inserizione',
            new_name='inserzione',
        ),
    ]
